language: python

python:
  - "3.6"

before_install:
  - pip install boto3
  - pip install pytest
  - pip install pytest-cov
  - pip install -r requirements.txt
  - pip install python-coveralls
  - pip install pylint

script:
  - python3 -m pytest tests/ --cov=tests

after_success:
  - coveralls
